### ISSUE TITLE
页面切换问题

### ISSUE THREAD

**Issue by codinglilong** [nanxiaobei/react-slide-routes#1]
我这也没切换为啥方向是反的，首页点进到about页面是从左边滑倒右边，退后的效果。。。

**Comment by nanxiaobei** [comment]
页面本身是用 `sessionStorage` 储存路由历史记录的，如果点了 about 然后刷新页面，可能出现这种情况。
可用 [`pathList`](https://github.com/nanxiaobei/react-slide-routes#api) 属性来精准控制路由前后顺序。
