### ISSUE TITLE
React.createElement: type is invalid

### ISSUE THREAD

**Issue by MoniikaL** [nanxiaobei/react-slide-routes#12]
Other people have mentioned this issue before but it was closed because no demo was provided, so here it is..

https://codesandbox.io/s/react-slide-routes-forked-xe4ds?file=/src/App.js

It happens when "Redirect" is used.

**Comment by nanxiaobei** [comment]
Thanks, it has been fixed, please try `1.1.0`.

**Comment by MoniikaL** [comment]
Thanks for the quick fix!
