### ISSUE TITLE
Animation does not work with nested pages from 2nd level onwards.

### ISSUE THREAD

**Issue by vahid-neuralinc** [nanxiaobei/react-slide-routes#14]
Hi,
Animation does not work with nested pages from 2nd level onwards for example I have a journey:

Home > Page 1 > Page 5 > Page 6
Home > Page 3
Home > Page 4

and my router looks like:

<SlideRoutes>
    <Route path="/home" element={<Page1 />} exact />
    <Route path="/page1" element={<Page1 />} exact />
    <Route path="/page2" element={<Page1 />} exact />
    <Route path="/page3" element={<Page1 />} exact />
    <Route path="/page4" element={<Page1 />} exact />
    <Route path="/page5" element={<Page1 />} exact />
    <Route path="/page6" element={<Page1 />} exact />
</SlideRoutes>

Here:
- Home calls Page 1 via useNavigate()
- Page 1 calls Page 5 via useNavigate()
- page 5 calls Page 6 via useNavigate()

- Home calls Page 2 via useNavigate()
- Home calls Page 3 via useNavigate()

Animation only works between:

- Home > Page 1
- Home > Page 2
- Home > Page 3

Animation does not work for the second level of the journey onwards

**Comment by nanxiaobei** [comment]
Yes, only the first level pages are supported.

**Comment by vahid-neuralinc** [comment]
I see, since I could not find it in the documentation, I thought it's a bug. Thanks a lot for clarification. It can go as a feature request though.
