### ISSUE TITLE
Slide order cannot be controlled (seems to be alphabetically sorted)

### ISSUE THREAD

**Issue by flying-sheep** [nanxiaobei/react-slide-routes#19]
See https://codesandbox.io/s/react-slide-routes-repro-ep9ovo:

Switching between “About” and “Home” goes in the wrong direction.

`pathList` might be a solution for simple cases, but it’s not sufficient if you have nested routes.

**Comment by nanxiaobei** [comment]
Yes, currently only `pathList` is support.

because the route `history` recorded by `react-slide-routes` is an array, an array can not recognize the "order" of routes, only record before or after.

**Comment by flying-sheep** [comment]
So what can we do to change that?

**Comment by nanxiaobei** [comment]
No way to do at present, can modify it yourself.
