### ISSUE TITLE
Cannot read properties of undefined (reading 'pathname')

### ISSUE THREAD

**Issue by Denny966** [nanxiaobei/react-slide-routes#21]
Using react router 5 with 1.1.1 gives the error 

Cannot read properties of undefined (reading 'pathname')

Demo:
https://codesandbox.io/s/react-slide-routes-forked-exqniq

**Comment by nanxiaobei** [comment]
`1.1.0` is for React Route v5, not like `2.0.0`, need to pass `location` prop manually to `SlideRoutes`.
can refer here: https://github.com/nanxiaobei/react-slide-routes/blob/367ff0dfa94c9ff3234fc55493c27e3a53996ccd/README.md

and the usage of `Route` in the demo is incorrect, it's v6 style, not v5 style.
