### ISSUE TITLE
More flexible route order

### ISSUE THREAD

**Issue by flying-sheep** [nanxiaobei/react-slide-routes#23]
In #22, I wanted to add a way for users to control route order that doesn't rely on a static `pathList`.

There's a few considerations here:

1. React router allows to generate content dynamically, therefore it might not be possible (or be very memory heavy) to create a static path list
2. The order of `Route`s has semantic meaning (the first matching one is rendered). I think my PR matches this behavior, so it should always look correct. Might need some unit tests
3. `react-router` has some additional code for nested routes that I didn't replicate in the PR. That needs to be added to work correctly when using `SlideRoutes` nested under another `*Routes` component
4. There's the case that the matched route indices are equal when navigating between two locations that are matched by the same route. My PR didn't handle that case, but we should either allow to specify an undirected transition for that case it just do none instead of an arbitrary directed one.

Also we could allow people to customize transition direction order on top of all that. I'd imagine a function with a signature like the `compareFn` argument of [Array.prototype.sort](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort).

**Comment by nanxiaobei** [comment]
Ok, thanks. 
You can continue to develop on the `2.2.0` version. After the PR is finished, I will merge it and may make some modifications.
