### ISSUE TITLE
Possible Feature: undirected transitions

### ISSUE THREAD

**Issue by flying-sheep** [nanxiaobei/react-slide-routes#27]
This would be an alternative use case compared to nested use as implemented in #24. If you want it, we can support both use cases, but I think nested use is more useful, so I’m implementing that first in my PR.

In order to do this, we’d add a prop `undirectedAnimation` or so and `CSSTransition`’s `key` has to be changed to something like this:

```ts
const key = undirectedAnimation
  ? relPath  // play transition for nested routes handled by nested `Routes` components
  : next.route.path ?? next.index  // leave things to a nested `SlideRoutes` component
```

  Setting that prop would disable nested use: You would use only one `SlideRoutes` component which would play an undirected transition for each more deeply nested navigation happening.

So once #24 is merged, we support nested `SlideRoutes`:

```tsx
const App = () => (
  <SlideRoutes>
    <Route path="1" element={
      <SlideRoutes animation="vertical-slide">
        <Route path="a" element="/1/a" />
        <Route path="b" element="/1/b" />
      </SlideRoutes>
    }/>
    <Route path="2" element="/2" />
  </SlideRoutes>
)
```

or if we also implement `undirectedAnimation`, we would also support one global `SlideRoutes` component with nested `Routes` component(s) below it:

```tsx
const App = () => (
  <SlideRoutes undirectedAnimation="fade">
    <Route path="1" element={
      <Routes>
        <Route path="a" element="/1/a" />
        <Route path="b" element="/1/b" />
      </Routes>
    }/>
    <Route path="2" element="/2" />
  </SlideRoutes>
)
```

**Comment by nanxiaobei** [comment]
I'd prefer the 1st solution, nested `SlideRoutes`.
I think no need to add a new prop `undirectedAnimation` and it's a little had to understand.

**Comment by flying-sheep** [comment]
OK, then let's just close this
