### ISSUE TITLE
`useMemo` has no effect

### ISSUE THREAD

**Issue by flying-sheep** [nanxiaobei/react-slide-routes#29]
As said before, I’m pretty sure this will always be re-rendered since `children` changes for every render:

https://github.com/nanxiaobei/react-slide-routes/blob/6e9f97bb62c5d9b0f8b295e0a0ab1562f92c3aac/src/index.tsx#L151
[…]
https://github.com/nanxiaobei/react-slide-routes/blob/6e9f97bb62c5d9b0f8b295e0a0ab1562f92c3aac/src/index.tsx#L179

So I think `useMemo` can simply be removed because it has no effect.

**Comment by nanxiaobei** [comment]
ok, `3.0.1` fixed this.
