### ISSUE TITLE
Great ! But How can I drag to slide pages  , Like Facebook mobile app

### ISSUE THREAD

**Issue by thanhtutzaw** [nanxiaobei/react-slide-routes#31]
my fb 
https://facebook-ui-zee.vercel.app
in desktop use shift + scroll to slide vertically

**Comment by nanxiaobei** [comment]
You need to handle the dragging gestures by yourself, and then trigger `navigate('/xxx')`. Dragging is not a function of this library.

**Comment by thanhtutzaw** [comment]
I used horizontal scroll section instead of routes . eg.   /#profile   instead of /profile
