### ISSUE TITLE
React.createElement: type is invalid 

### ISSUE THREAD

**Issue by TomasKuruc** [nanxiaobei/react-slide-routes#7]
I'm notice, that using this package with typescript throws warnings :

React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

**Comment by nanxiaobei** [comment]
Please provide a reproducible demo.

**Comment by flying-sheep** [comment]
#24 should fix this. It skips all non-`Route` elements while iterating over `Routes` children, not just those with the `replace` prop set.
