### ISSUE TITLE
Cannot read property of 'location '...undefined

### ISSUE THREAD

**Issue by John-Oula** [nanxiaobei/react-slide-routes#8]
react-dom: ^17.0.2
    react-router-dom: ^5.2.0
    react-slide-routes: ^0.14.0,

imported all modules

function Home() {
    const location = useLocation();

    return (

        <Router>
          <AuthProvider>
              <LoaderProvider>

              <UserProvider>

              <ChatProvider>

              <EventProvider>
          <FormProvider>

          <Switch>
              <SlideRoutes location={location}>

              <Route path="/" component={Home} />
              <Route path="/signup" component={Signup} />
              <Route path="/events" component={Events} />
              <Route path="/eventDetails/:id" component={EventDetails} />
              <Route exact path="/user/:id" component={UserProfile} />
              <Route exact path="/user/:id/joined-events" component={JoinedEvents} />
              <Route exact path="/user/:id/created-events" component={CreatedEvents} />
              <Route exact path="/user/:id/create-schedule" component={CreateSchedule} />
              <Route exact path="/user/:id/deposit" component={Deposit} />
              <Route exact path="/user/:id/withdraw" component={Withdraw} />
              <Route exact path="/messages" component={Message} />
              <Route path="/messages/:id" component={Message} />
              </SlideRoutes>

              <div className="home">

<div>
                  <Hero/>
                  <Features/>
                  <Performance/>
                  <DownloadLinks/>
                  <Testimonials/>
                  <ContactUs/>
                  <Footer/>
</div>

              </div>
          </Switch>
          </FormProvider>
            </EventProvider>
                  </ChatProvider>

                  </UserProvider>
              </LoaderProvider>

          </AuthProvider>

      </Router>
  );
}

**Comment by nanxiaobei** [comment]
Please provide a reproducible demo.
